spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
server.error.include-message=never
server.error.include-binding-errors=never
app.cookie.secure=true
app.cookie.same-site=None
management.endpoint.health.show-details=never
app.seed.demo-catalog=false
spring.flyway.clean-disabled=true
